name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        node: ["18"]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
    env:
      MONGODB_URI: mongodb://localhost:27017/smart-payment-notification
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

  # coverage:
  #   name: coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: "18"
  #     - run: npm install -g yarn
  #     - run: yarn install
  #     - run: yarn build
  #     - uses: paambaati/codeclimate-action@v3.1.1
  #       env:
  #         CC_TEST_REPORTER_ID: ef6a4b3e0ecc9a831db6e99fc412284e8c67e6a5d0e85718204e7b2a25f0e415
  #       with:
  #         coverageCommand: yarn coverage
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build the app
        run: yarn build

      - name: Deploy the app to production
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
